### ISSUE TITLE
Download Section

### ISSUE THREAD

**Issue by KomuroDev** [Perseus/topcms#21]
Mostly important:
- Create sections for client, patches and other downloads.
- Field to add a version number on the download.
- Field to add a description of the download.

More Details On Downloads:
- Create unique fields if a links corresponds to MEGA (for example), if a link is placed there, then display a little MEGA icon on the generated download link instead of displaying the link itself.
- This can be done for MEGA, MediaFire, Google Drive and other known sites.
- If a link doesn't not belong to a known site, then place generic icon for each unknown site.

**Comment by Perseus** [comment]
Done in #24
