### ISSUE TITLE
Item Mall - Items Not Available

### ISSUE THREAD

**Issue by KomuroDev** [Perseus/topcms#61]
Added a new item onto Item Mall under a category and it is not showed. The item says it is there and under the category, but the category says it has no item.

![Capture](https://user-images.githubusercontent.com/24204159/83104301-51a70080-a06d-11ea-91cd-19c22196fea8.PNG)
![Capture](https://user-images.githubusercontent.com/24204159/83104268-3e943080-a06d-11ea-82be-5444190b4db6.PNG)

**Comment by Perseus** [comment]
Was a caching issue in the frontend. Categories were being cached if you opened them before creating the item and not re-fetched when you went back to the categories page. Disabled caching for mall categories.
Fixed in #62
